Create DATABASE customer_behavior;
SELECT * FROM customer limit 20;
 
 -- Total rev generated by male vs female customer.
 Select gender, SUM(purchase_amount) as revenue
 FROM customer
 GROUP BY gender;
 
 -- customers used a discount  but still spent more than the average purchase amount
 select customer_id, purchase_amount
 from customer
 where discount_applied = 'Yes'
  and purchase_amount >= 
  (select AVG(purchase_amount )
  FROM customer);
  
  -- top 5 product with the highest avg review rating
  
  SELECT item_purchased, AVG(review_rating) as "Average Product Rating"
  FROM customer
  group by item_purchased
  order by avg(review_rating) desc
  limit 5;
  
  -- compare the avg purchase amount between Standard ad express shipping
  
  select shipping_type,
  ROUND(
  AVG(purchase_amount),2)
  FROM customer
  WHERE shipping_type in('Standard','Express')
  group by shipping_type;
  
  -- dO subscribed customers spend more? Compare avg spend and total revenue 
  -- between subscriber's and non-subscribers.
  SELECT subscription_status,
  COUNT(customer_id) as total_customers,
  ROUND(AVG(purchase_amount),2) as avg_spend,
  ROUND(SUM(purchase_amount),2) as total_revenue
  FROM customer
  group by subscription_status
  order by total_revenue,avg_spend desc;
  
  -- which 5 product have the highesr percentage of purchase with discount applied
  SELECT item_purchased,
  ROUND(
  (SUM(CASE WHEN  discount_applied = 'Yes' THEN 1 ELSE 0 END)
  /COUNT(*) * 100.0) ,2 )AS discount_rate
  FROM customer
  group by item_purchased
  order by discount_rate desc
  limit 5;
  
  -- Segment customer into NEW , returning and loyal based on their total 
  --  number of previous purchases, show the count of each segment
  
  WITH customer_type as (
  select customer_id,previous_purchases,
  CASE
	WHEN previous_purchases = 1 then 'New'
    WHEN previous_purchases between 2 and 10 then 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer
)
SELECT customer_segment , count(*) as "Number of Customers"
FROM customer_type
group by customer_segment;

  -- top 3 most purchased products within each category
  
WITH item_counts as (
SELECT category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3;

-- are customers who are repeat buyers (more then 5 previous purchase) also likely to subscribe

select subscription_status,
count(customer_id) as repeat_buyers
FROM customer
where previous_purchases > 5
group by subscription_status;

-- what is the revenue contribution of each age group

select age_group,
SUM(purchase_amount) as total_revenue 
from customer
group by age_group
order by total_revenue desc;



  
 
 
 

